#!/bin/bash
# Create new MySQL database,
# download & install latest stable Conato to $DOCUMENTROOT/$PROJECT/contao
# and link "public" to "contao"

# Environment-configurable variables
MYSQLUSER=root
MYSQLPASS=rootPW
CMSUSER=user
CMSPASS=userPW
HOST=localhost
DBPREFIX=contao_
DOCUMENTROOT=$HOME/www
LANG=de
MYSQL=`which mysql`
DIR=$(pwd)

# Read userconfig if available
if [ -r ~/.contash ]; then
  source ~/.contash
fi

# Check for arguments
if [ $# -lt 1 ]
then
  echo "USAGE: contash project|domainname";
  echo "New MySQL database requires at least one argument (the name of the project to create a development database for = domain name)."
  echo "Aborting..."
  exit
fi

PROJECT="$1"
DBNAME=$DBPREFIX${PROJECT//-/_}

Q1="CREATE DATABASE IF NOT EXISTS $DBNAME;"
Q2="GRANT ALL ON $DBNAME.* TO '$CMSUSER'@'$HOST' IDENTIFIED BY '$CMSPASS';"
Q3="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}${Q3}"

# Execute database creation
$MYSQL -u$MYSQLUSER -p$MYSQLPASS -e "$SQL"

# Check whether database was created
RESULT=$($MYSQL -u$CMSUSER -p$CMSPASS -e "SHOW DATABASES LIKE '$DBNAME';")
if [ -n "$RESULT" ]
then
  echo "A database has been created with the name set to $DBNAME."
  echo "User set to $CMSUSER and password set to $CMSPASS."
else
  echo "Oops – Something went wrong! The database could not be created or the new user has no access."
  echo "Aborting..."
  exit
fi

# Create project directory in $DOCUMENTROOT
echo "Creating $DOCUMENTROOT/$PROJECT"
mkdir "$DOCUMENTROOT/$PROJECT"

# Download and extract latest stable Contao
curl -Lo $DOCUMENTROOT/$PROJECT/contao.zip https://download.contao.org/zip
unzip -q $DOCUMENTROOT/$PROJECT/contao.zip -d $DOCUMENTROOT/$PROJECT
rm $DOCUMENTROOT/$PROJECT/contao.zip

# Read current version from CHANGELOG.md
VERS=$(grep -om 1 "Version \([0-9].\)*" $DOCUMENTROOT/$PROJECT/*/system/docs/CHANGELOG.md)
VERS=${VERS:8}
SITEROOT=$DOCUMENTROOT/$PROJECT/cms/$VERS

# Move core-master to contao/[current version]
mv  $DOCUMENTROOT/$PROJECT/* $DOCUMENTROOT/$PROJECT/$VERS
mkdir $DOCUMENTROOT/$PROJECT/cms
mv  $DOCUMENTROOT/$PROJECT/$VERS $SITEROOT

# Copy localconfig.php to contao/[current version]/system/config/
cp $DIR/localconfig.php $SITEROOT/system/config/
# Fill in database name and latest version
sed -i "" "s/%%DBNAME%%/$DBNAME/" $SITEROOT/system/config/localconfig.php
sed -i "" "s/%%CURVERS%%/$VERS/" $SITEROOT/system/config/localconfig.php

# Create folders named $PROJECT in /files and /templates
mkdir $SITEROOT/files/$PROJECT
touch $SITEROOT/files/$PROJECT/style.css
touch $SITEROOT/files/$PROJECT/main.js
mkdir $SITEROOT/files/$PROJECT/images
mkdir $SITEROOT/files/$PROJECT/images/site
mkdir $SITEROOT/files/$PROJECT/images/theme
mkdir $SITEROOT/templates/$PROJECT

# Create public symlink to contao/[current version]
ln -s $SITEROOT $DOCUMENTROOT/$PROJECT/public

# Open installtool in browser if server is running
RUNNING=$(ps ax | grep "httpd" | wc -l)
if [ $RUNNING -gt 1 ]; then
  open "http://localhost/contao/$PROJECT/public/contao/install.php"
fi
